ci: add missing compression tools to debian container
```text
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/usr/bin/tar: Child returned status 2
/usr/bin/tar: Error is not recoverable: exiting now
Error: The process '/usr/bin/tar' failed with exit code 2
    at $1cb7748a0c6124b0$var$ExecState._setResult (/__w/_actions/KyleMayes/install-llvm-action/v2/dist/main.js:1386:92)
    at $1cb7748a0c6124b0$var$ExecState.CheckComplete (/__w/_actions/KyleMayes/install-llvm-action/v2/dist/main.js:1375:38)
    at ChildProcess.<anonymous> (/__w/_actions/KyleMayes/install-llvm-action/v2/dist/main.js:1295:31)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
```